### ISSUE TITLE
B.E.N.J.I. not working properly

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#1]
The assistant is not hearing voice commands. Most of the commands have to be typed out. Secondly, only some commands are working. We need to to look into it.

**Comment by NIteshx2** [comment]
This issue is'nt yet fixed ? I had created on such assistant . Maybe that could help . 
https://github.com/NIteshx2/PyAssistant

**Comment by the-ethan-hunt** [comment]
If you would like to work on it, I will assign this issue to you.

**Comment by Yatish04** [comment]
@the-ethan-hunt  you can close his issue also

**Comment by the-ethan-hunt** [comment]
Closing it down for now
