### ISSUE TITLE
Update Readme with working of B.E.N.J.I. on Mac OS

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#103]
Take a `.gif` and post it in `readme.md`  to show the working of B.E.N.J.I. on Mac OS

**Comment by angelapwen** [comment]
I've got the .gif ready and will post and edit the README. I also have some extra setup comments to add to the README; should this be a separate issue or could I do them together here?

**Comment by angelapwen** [comment]
@the-ethan-hunt could you assign this to me and let me know about the question above? Thanks!

**Comment by the-ethan-hunt** [comment]
@angelapwen it has been assigned to you. :smile:
