### ISSUE TITLE
After KWoC

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#104]
KWoC has turned out be a really fruitful period. Now, we need to work more on B.E.N.J.I.. Those interested please ping me here. Both KWoC participants and non-participants are welcomed to join!

**Comment by NIteshx2** [comment]
I'd definitely want to see how me make this, or any code modular, and a .exe file, if possible!

**Comment by Kitwradr** [comment]
I would love to work on this

**Comment by the-ethan-hunt** [comment]
The work might be a little under-stressed now but I will still not allow laziness.
- @NIteshx2 , I will certainly **not allow** the dilly-dallying you did in KWoC. Secondly, I don't know where you would help me out. Please explain what you can do in the project
- @Kitwradr , the same thing. I don't know how you might help. Can you explain me?

**Comment by Kitwradr** [comment]
Can you tell me what I should do and the timeline by when I should complete it . I will tell you whether I can do it.

**Comment by kb-studios** [comment]
I would like to continue with this project! 😄

**Comment by abhimanyuthakre** [comment]
I am interested to work on this project further!

**Comment by kb-studios** [comment]
I would like to continue on this project! 😄

**Comment by Yatish04** [comment]
Me too

**Comment by gautamramuvel** [comment]
I am also interested to work !!

**Comment by the-ethan-hunt** [comment]
- @Kitwradr what I meant is what are you proficient in? Code modularity, NLP or DL or anything else? 
- @gautamramuvel , same question goes for you
- @Yatish04 , I want faster responses from you when I comment on your PR or send you a message(within 3-4 days)
We will wait for 21st January to start working back. In the meantime, you can study up something out of these:
- Making B.E.N.J.I. cross-platform
- This [issue](https://github.com/the-ethan-hunt/B.E.N.J.I./issues/83)
- Can we connect B.E.N.J.I. to household devices and electricity supply?
- Can also use it as a chatbot?
- Any other AI prospect I missed.

We can also work on some other features. But I suggest features will now be a lower priority. With each new version, we might release a new feature(AGILE system)
P.S. Please be responsive on the Slack channel too.

**Comment by the-ethan-hunt** [comment]
@Kitwradr , no problem. I suggest you start with the `good first issues`. They are generally related to documentation and can be done easily. Also, you can study up something as I mentioned in my previous message

**Comment by the-ethan-hunt** [comment]
Hello All! It's been a while since we talked. Please discuss what you might have read or done during this period on the slack channel.

**Comment by the-ethan-hunt** [comment]
Pinging all! Where have you all been? :smile: . I got one question from @NIteshx2 and the others have not contacted me as of yet.

**Comment by Kitwradr** [comment]
@the-ethan-hunt can you check issue #33 for my comments if you're ok with it i'll send PR

**Comment by the-ethan-hunt** [comment]
Closing this issue due to stagnation
