### ISSUE TITLE
Chat on slack link not working 

### ISSUE THREAD

**Issue by omi10859** [the-ethan-hunt/B.E.N.J.I.#107]

**Comment by the-ethan-hunt** [comment]
The slack link is working properly. Closing this issue

**Comment by omi10859** [comment]
![screen shot 2018-06-10 at 3 15 09 pm](https://user-images.githubusercontent.com/26123416/41200370-19fbc846-6cc1-11e8-9333-0b9ebbff6707.png)
I'm getting this :(
