### ISSUE TITLE
Make B.E.N.J.I. Compatible on win64 bit

### ISSUE THREAD

**Issue by NIteshx2** [the-ethan-hunt/B.E.N.J.I.#11]
While trying to run BENJI , i'm unable to import wx on pycharm 64bit. Need a workaround.

**Comment by NIteshx2** [comment]
The news parts don't seem to be working on win64

**Comment by the-ethan-hunt** [comment]
The thing with news part is you need to have your own `API key` for each news bulletin. Check it on the website.

**Comment by kb-studios** [comment]
Tested the linux version of B.E.N.J.I. on 64-bit Windows (64-bit python).
With a little modification in the imports (the imports and now conditional, so it imports the correct modules according to the OS) and requirements.txt, the code successfully ran on a windows machine,
I guess we now have a **Cross-Platform B.E.N.J.I**!

**Comment by the-ethan-hunt** [comment]
@kb-studios can you also run the tests on windows 32-bit? (Hint: virtual machine)

**Comment by kb-studios** [comment]
Would running it on a 32-bit python do the job? As my pc has a x86 architecture.

**Comment by kb-studios** [comment]
@the-ethan-hunt the code is working perfectly on 32 bit python too.

**Comment by the-ethan-hunt** [comment]
That's great @kb-studios ! :tada:  I wonder why it's not running on my device.

**Comment by kb-studios** [comment]
@the-ethan-hunt What exactly is the error?

**Comment by kb-studios** [comment]
The current master branch doesn't run on windows. I made a few changes to the file. (The import section) and then it started working

**Comment by the-ethan-hunt** [comment]
@kb-studios , I would suggest keeping the windows and Linux sections separately. After we get the MAc OS version, we can have a cross-platform B.E.N.J.I.

**Comment by kb-studios** [comment]
@the-ethan-hunt The only problem we are facing right now as of now by keeping two different versions is, the features added and the bugs fixed on the Windows version are not available to us. So how do we add those features to Linux version now? Making it cross-platform as soon as possible would mean that both Windows and Linux users could contribute together. Just my opinion. :-)
I respect your decision, and would keep them as separate files now. 👍

**Comment by the-ethan-hunt** [comment]
Nice thoughts @kb-studios ! How about creating a folder titled "cross-platform" where you can tinker with the main code without affecting the original windows code. At the end of the coding period, I will merge it all. :smile:

**Comment by kb-studios** [comment]
@the-ethan-hunt Sure, will go for it. We can keep this code for people to test! :smiley:
