### ISSUE TITLE
B.E.N.J.I. to recognize user

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#112]
OpenCV might help in this case. If the user has not the right permissions, then B.E.N.J.I will directly shut down the system. The owner will have the permission to add any other user if he/she wishes to.

Assigned to @abhimanyuthakre

**Comment by shubhpatel108** [comment]
As a starting point, password based authentication should work fine?

We can use the standard Role-Resource-Privilege model irrespective of the input mode.
