### ISSUE TITLE
Add a reminder feature

### ISSUE THREAD

**Issue by CodHeK** [the-ethan-hunt/B.E.N.J.I.#116]
Desp: The feature must be such that the user must be able to set events which directly get updated in the pc's calender. 
Eg: If the user types in "Farewell Party on 23/7/18 (some date format) at 6pm" it needs to directly upatde as an event on the calender

**Comment by hmangukia** [comment]
Can I work on this issue @the-ethan-hunt ?

**Comment by hmangukia** [comment]
I am working on adding event on the Google Calendar, @CodHeK @the-ethan-hunt, and so it will also remind the user on that particular day.

**Comment by the-ethan-hunt** [comment]
Alright @hmangukia .

**Comment by hmangukia** [comment]
Please review the PR and let me know if any changes need to be made 😄

**Comment by sara-02** [comment]
@the-ethan-hunt Since PR #122 is merged, we can close this now.
