### ISSUE TITLE
Updates required in the README.md

### ISSUE THREAD

**Issue by sara-02** [the-ethan-hunt/B.E.N.J.I.#121]
The list of updates required are

- [ ] Under Note 1, list GSSoC as well. NOTE1 can be rewritten as `BENJI has participated in the following Open Source Programs: Kharagpur Winter of Code 2017, GirlScript Summer of Code 2018`
- [ ] Under Note 1: The link to KWoC is broken, better not to create any hyperlink.
- [ ] Under Note2: The link to the Open Source Summit is broken.

**Comment by AneriMehta** [comment]
I would like to contribute and update the README file.

**Comment by the-ethan-hunt** [comment]
Assigned to @AneriMehta
