### ISSUE TITLE
Add a pylinter.sh for local testing.

### ISSUE THREAD

**Issue by sara-02** [the-ethan-hunt/B.E.N.J.I.#129]
Add a bash script to check for linting issues, so that contributors can have their code properly linted before submitting the pull request.
Files required to be added
1.  `pylinter.sh` Eg: https://github.com/fabric8-analytics/f8a-hpf-insights/blob/master/run-linter.sh
2.  `setup.cfg` Egs: https://github.com/fabric8-analytics/f8a-hpf-insights/blob/master/setup.cfg and/or https://github.com/systers/sysbot/blob/develop/setup.cfg

**Comment by Man-Jain** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by the-ethan-hunt** [comment]
Assigned to @Man-Jain

**Comment by Man-Jain** [comment]
@sara-02 Can you please specify what parameters should I add in the setup.cfg file.

**Comment by sara-02** [comment]
@Man-Jain Let us ignore only `W504`. So our file should look like
```python
[pycodestyle]
ignore = W504
max-line-length = 80
```
List of all configurations, http://pycodestyle.pycqa.org/en/latest/intro.html

**Comment by sara-02** [comment]
@the-ethan-hunt Do you have any preferences? Especially with `max-line-length`

**Comment by sara-02** [comment]
You will have to fix them. So you will basically create 2 PR, one with the scripts, and other with the corrected code, fixing indents and rest of error.

**Comment by the-ethan-hunt** [comment]
@Man-Jain since this requires 2 PR and considerable work, I am extending the GSSoC score for this to Pro

**Comment by sara-02** [comment]
@Man-Jain yes, errors will be there. Lets send a PR one file at a time. run the linter script for the first time, and see the final result x/y files need fixing. Then pick of the files, improve it accoring to the suggestions given by the linter, and then run the script again. This time you should see x-1/y files need fixing. Send a PR for that fixed file, and so on.

**Comment by Man-Jain** [comment]
@sara-02 But this process will take a lot of time as there are a lot of files with lot of errors.

**Comment by sara-02** [comment]
@Man-Jain You don't have to be the only one working on this issue. Also, all modern text editors and IDEs come with autopep8 compliance. So if you open an unformatted file, upon saving they will format it according to the pep8 standards. So you manually do not have to do it, except for opening and saving the files once in the IDEs.
