### ISSUE TITLE
Create requirements.txt 

### ISSUE THREAD

**Issue by NIteshx2** [the-ethan-hunt/B.E.N.J.I.#13]
Have you considered using `pip` and having a file namely `requirements.txt`? In that way you can directly install the dependencies using `pip install -r requirements.txt` .

**Comment by the-ethan-hunt** [comment]
A nice issue for a first-timer :smile:

**Comment by kb-studios** [comment]
I am willing to work on this issue

**Comment by the-ethan-hunt** [comment]
You are welcome to work on it :smile:

**Comment by the-ethan-hunt** [comment]
We have received a PR regarding this some time ago. How about you solve some other cool issue?

**Comment by the-ethan-hunt** [comment]
closing this issue for now
