### ISSUE TITLE
Add Doctsrings: Improve Documentation

### ISSUE THREAD

**Issue by sara-02** [the-ethan-hunt/B.E.N.J.I.#136]
The project requires doc-strings support for the implemented functions and classes. It will help in an easier understanding of code for newcomers.
The best way is to follow the Python's PEP8 Docstring convention.
More details here: https://www.python.org/dev/peps/pep-0257/

**Comment by sourabh1031** [comment]
@sara-02 i will be taking up the issue

**Comment by sara-02** [comment]
@sourabh1031 sure.

**Comment by agarwalrounak** [comment]
I will work on it.

**Comment by the-ethan-hunt** [comment]
Assigned to @agarwalrounak
