### ISSUE TITLE
Add a Gitter badge

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#141]
We will now chat on Gitter! Here's the [link](https://gitter.im/B-E-N-J-I/Lobby)
Remove the Slack link.

**Comment by rahulkumaran** [comment]
I'd like to take this up, if nobody's already working on this.

**Comment by the-ethan-hunt** [comment]
Sure. Assigned to @rahulkumaran
