### ISSUE TITLE
Make a list of contributors.md

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#17]
As contributors keep increasing, we can make a `contributors.md` to list their names and recognize their efforts :smile:

**Comment by rishabh0098** [comment]
I can do this

**Comment by the-ethan-hunt** [comment]
Sure, but we need this at the end(or the middle of the coding duration) when there are a significant number of the contributors. I am however, assigning this issue to you

**Comment by Snehal-Reddy** [comment]
It will always be there in insights-contibutors , right ? What is the use of a separate file ?[https://github.com/the-ethan-hunt/B.E.N.J.I./graphs/contributors](url)
