### ISSUE TITLE
Change the commands

### ISSUE THREAD

**Issue by BrianMwangi21** [the-ethan-hunt/B.E.N.J.I.#19]
Hi, newbie here but willing to contribute to this project.

I would like to work on the commands, eg "who are you " should work the same with "who are you" and "Who are you" or any combination.

Either change all input strings to small letters then strip the spaces after or something. How is that ?

**Comment by the-ethan-hunt** [comment]
Sounds cool. You can also try  "who r u". Assigning the issue to you

**Comment by BrianMwangi21** [comment]
Thanks

**Comment by aniketgattani** [comment]
@BrianMwangi21 are u working on this issue? If not I would like to contribute

**Comment by BrianMwangi21** [comment]
Already worked on it and the pull request was merged
