### ISSUE TITLE
Improve ReadMe

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#2]
The declassified debrief should add up in the background. We need to write more about how B.E.N.J.I should be working and what are its requirements. We also need to include the screenshots of its working.

**Comment by the-ethan-hunt** [comment]
B.E.N.J.I. is now working for Linux too :tada:  Please include this in the `readme.md`

**Comment by vchrombie** [comment]
Hello, I am interested in this project.
Can I help you?

Can I add some screenshots of B.E.N.J.I, working in linux?

**Comment by nityanandagohain** [comment]
@the-ethan-hunti i have submitted a pr #48
