### ISSUE TITLE
Make B.E.N.J.I. compatible with Mac OS

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#23]
We are working on compatibility issues with Linux. We would also like to work on Mac Os for the same

**Comment by rishabh0098** [comment]
Is there any way to work on this issue without having a MacBook ??

**Comment by kb-studios** [comment]
You can use a Virtual Machine to do so. I feel the current linux version my be compatible with mac, you can try running that code on the VM.

**Comment by Snehal-Reddy** [comment]
Done , B.E.N.J.I is now working on MacOS. Pull request #91
