### ISSUE TITLE
Create a new logo

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#24]
B.E.N.J.I. is having quite an old-fashioned logo. Indulge your creativity to make a new awesome logo :tada:

**Comment by Snehal-Reddy** [comment]
![b e n j i](https://user-images.githubusercontent.com/32029011/33527972-ba72b41e-d87f-11e7-840c-b78fff5bede2.jpg)
How's the logo ?

**Comment by Snehal-Reddy** [comment]
![b e n j i](https://user-images.githubusercontent.com/32029011/33528061-46956d32-d881-11e7-914b-a2e9d3029df9.jpg)
hows the logo ?

**Comment by Snehal-Reddy** [comment]
![benjifinal](https://user-images.githubusercontent.com/32029011/33528629-ea6a39b2-d889-11e7-9747-092d92019ba3.jpg)
how's this ?

**Comment by the-ethan-hunt** [comment]
Excellent!!

**Comment by the-ethan-hunt** [comment]
@Snehal-Reddy , please submit a PR for this logo. :tada:

**Comment by the-ethan-hunt** [comment]
Closing this issue.
