### ISSUE TITLE
news and cricket not working

### ISSUE THREAD

**Issue by Yatish04** [the-ethan-hunt/B.E.N.J.I.#28]
All the news and  features are not working

**Comment by BrianMwangi21** [comment]
lemme send you a video of them working

**Comment by Yatish04** [comment]
Nothing is happening when i test for cricket and news in mine

**Comment by BrianMwangi21** [comment]
<iframe class="imgur-embed" width="100%" height="630" frameborder="0" src="https://i.imgur.com/wx2aEFu.gifv#embed"></iframe>

**Comment by Yatish04** [comment]
try typing just bbc

**Comment by BrianMwangi21** [comment]
unless you change `elif put.startswith('bbc ')` to `elif put.startswith('bbc')`

**Comment by the-ethan-hunt** [comment]
Closing this issue for now
