### ISSUE TITLE
Breaking the code into modules

### ISSUE THREAD

**Issue by Yatish04** [the-ethan-hunt/B.E.N.J.I.#31]
It will be helpful to debug if we can break this large code into smaller modules so that debugging is easy.

**Comment by kb-studios** [comment]
I would like to contribute to this!
More discussion on this topic can be done before implementing as to how this can be done optimally (so as to not break any existing code), what design patterns to use, etc.

**Comment by the-ethan-hunt** [comment]
I agree partly with @kb-studios . We can hold a discussion [here](https://github.com/the-ethan-hunt/B.E.N.J.I./issues/32)

**Comment by sara-02** [comment]
@the-ethan-hunt Since the main discussion is happening on issue #32 , we can mark this issue as duplicate and close it.

**Comment by the-ethan-hunt** [comment]
Assigning to @srishilesh from Issue #32
