### ISSUE TITLE
Update readme with working of B.E.N.J.I. on windows

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#33]
Take a `.gif` and post it on `readme.md` to show the working of B.E.N.J.I. on Windows

**Comment by vchrombie** [comment]
Can I take this issue?
I will work on it.

**Comment by the-ethan-hunt** [comment]
@vchrombie , you have already solved a `good first issue`. Please leave it for another newbie :smile:

**Comment by vchrombie** [comment]
Okay,
If no one takes it, can you give it to me?

**Comment by AnirbanBanik1998** [comment]
I will work on it

**Comment by the-ethan-hunt** [comment]
@AnirbanBanik1998 , sure !

**Comment by Kitwradr** [comment]
![my-movie1](https://user-images.githubusercontent.com/26614919/35182688-93a70538-fdff-11e7-81d2-9872670d5a39.gif)

**Comment by Kitwradr** [comment]
is this fine @the-ethan-hunt

**Comment by Kitwradr** [comment]
Any suggestions?

**Comment by the-ethan-hunt** [comment]
Sorry for not noticing this @Kitwradr :sweat_smile: . Please make a PR for this. Closing this issue for now
