### ISSUE TITLE
Add badges 

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#35]
Add badges of 'works on Windows' , 'works on Linux', 'made with :heart: in Python' in `readme.md`

**Comment by vchrombie** [comment]
I am interested in this project.
Can I take this issue?

**Comment by vchrombie** [comment]
I submitted a PR #38.
Can you please review it and inform me for any changes.

**Comment by the-ethan-hunt** [comment]
Closing this issue
