### ISSUE TITLE
Unable to run on Linux

### ISSUE THREAD

**Issue by CaptainDaVinci** [the-ethan-hunt/B.E.N.J.I.#37]
I have tried installing the dependencies from `./linux/requirements-linux.txt`  however I am facing problems with certain modules. `pyttsx` gives an import error in python3, for python3 `pyttxs3` is required.

**Comment by the-ethan-hunt** [comment]
@kb-studios , please take a look at this issue

**Comment by kb-studios** [comment]
For me, pyttsx worked in Linux. But while testing it out on windows I had to go for pyttsx3. Ok then its better that we go with pyttsx3.
For the windows version I did
`import pyttsx3 as pyttsx`
This fix worked, as I didn't have to re-factor the rest of the code.

**Comment by kb-studios** [comment]
```
import wx
import re
import os
import wikipedia
import time 
import webbrowser 
import json
import requests
import ctypes 
import random
import urllib
import ssl
from bs4 import BeautifulSoup
try:
	from urllib import urlopen
except:
	try:
		from urllib.request import urlopen
	except:
		print("urllib is not installed")
import speech_recognition as sr
import requests
try:
	import pyttsx
except:
	try:
		import pyttsx3 as pyttsx
	except:
		print("Pyttsx not installed")
```

For now, am doing the imports this way. So as to avoid any sorts of errors while configuring the dependencies.

**Comment by Yatish04** [comment]
@kb-studios is the youtube play working in linux?
