### ISSUE TITLE
Make B.E.N.J.I. compatible with Linux

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#4]
Currently, the digital assistant is compatible only with Windows.

**Comment by kb-studios** [comment]
Should a new file be created for the linux version? Because the imports and functions could vary!
Eg. benji-linux.py

Or do we continue on the same file and make it compatible for linux.

**Comment by the-ethan-hunt** [comment]
Making a new file is better. You can name it as `linux/benji.py` and mention about this in the `readme`

**Comment by kb-studios** [comment]
Made a PR. I used `pyttsx` which is supposed to be cross-platform. So the file I wrote is platform-independent. (is supposed run on a mac too, haven't tested it). 
I feel keeping the Linux version in a separate file may be a problem, as the features added to the main file are not reflected here.

**Comment by the-ethan-hunt** [comment]
Closing this issue for now
