### ISSUE TITLE
Windows Open Website doesn't complete the webpage name

### ISSUE THREAD

**Issue by GS3207** [the-ethan-hunt/B.E.N.J.I.#41]
If I type open facebook it tries to access www.facebook .Adding a .com after it will solve the issue.

**Comment by abhimanyuthakre** [comment]
@GS3207 You have to mention top level domain like "open facebook.com" with the ".com" at the end. If you add ".com" directly into the code, then benji will search only for the ".com" domains. But now, it gives results for every webpage like "python.org", "amazon.in", etc.
