### ISSUE TITLE
Create setup.py

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#44]
We need to have a `setup.py` for both `Windows` and `Linux` versions of B.E.N.J.I. Please look [here](https://github.com/kennethreitz/setup.py) to know what actually this file contains

**Comment by falconis** [comment]
Can I work on this?

**Comment by the-ethan-hunt** [comment]
Sure @falconis !

**Comment by falconis** [comment]
Thanks!

**Comment by the-ethan-hunt** [comment]
Closing this issue now
