### ISSUE TITLE
List out what B.E.N.J.I. can do

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#49]
Make an `activities.md` to list what B.E.N.J.I. can do. For Linux one, make the markdown in the `Linux` folder. For windows version, make it in the `windows` version.

**Comment by jitShaw7** [comment]
Will like to work on it

**Comment by the-ethan-hunt** [comment]
Yes, sure!

**Comment by lapalb** [comment]
I think this issue is resolved now. It's better to close it.
