### ISSUE TITLE
Improve GUI

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#5]
B.E.N.J.I. is having a very primeval GUI as of now. Having a great, attractive GUI would make it look more attractive :smile:

**Comment by nityanandagohain** [comment]
i want to work on this

**Comment by rohanricky** [comment]
@nityanandagohain go ahead

**Comment by eulerkochy** [comment]
Well I am intrigued by your project and wish to contribute..I will develop the GUI using Tkinter if you assign me the job to do so.

**Comment by eulerkochy** [comment]
I will construct GUI for deployment only...you can add another issue for its testing!!

**Comment by the-ethan-hunt** [comment]
The issue has been resolved :smile:
