### ISSUE TITLE
Cannot open any webpages (linux version)

### ISSUE THREAD

**Issue by aribalam** [the-ethan-hunt/B.E.N.J.I.#52]
Their is a logical error code for opening webpages. The problem is in parsing the url link. It omits the 'dot' before 'com' and searches for the wrong address.
For eg. it opens 'facebookcom' instead of facebook.com.

**Comment by the-ethan-hunt** [comment]
@abhimanyuthakre , please provide the essential insight here :smile:

**Comment by abhimanyuthakre** [comment]
Comment out 199th line of benji.py and it will work fine.

**Comment by aribalam** [comment]
that fixed it! @abhimanyuthakre Can you just tell me what did that sub() function do?

**Comment by abhimanyuthakre** [comment]
sub() stands for substitute. It substituted the characters in the first parameter with the character mentioned in second parameter. This was the cause behind the removal of '.' from 'facebook.com'

**Comment by aribalam** [comment]
Ok thanks a lot.

**Comment by abhimanyuthakre** [comment]
You're welcome
