### ISSUE TITLE
Duplicate windows

### ISSUE THREAD

**Issue by the-ethan-hunt** [the-ethan-hunt/B.E.N.J.I.#64]
The `Linux` version of B.E.N.J.I. get two command windows. This bug must be removed

**Comment by kb-studios** [comment]
This is as in 2 GUI pop-ups being displayed? One being the BENJI window, and an extra blank window?
Fixed this issue! 😄

**Comment by the-ethan-hunt** [comment]
Great @kb-studios ! Just closing this issue
