### ISSUE TITLE
lookfor feature not working

### ISSUE THREAD

**Issue by rohanricky** [the-ethan-hunt/B.E.N.J.I.#72]
`put1.startswith`, but put1 does not exist.
Also can someone reproduce the feature, it doesn't seem to work.

**Comment by rishabh0098** [comment]
The above code is obsolete.
the feature is working only for windows yet, I'm working on the linux part.
you can also give any suggestions and codes.

**Comment by the-ethan-hunt** [comment]
PR #74 not improving it. The file feature is not working in Windows as well. :confused:

**Comment by the-ethan-hunt** [comment]
@rishabh0098 , care to explain :smile: ?

**Comment by the-ethan-hunt** [comment]
Closing this issue for PR #74
