### ISSUE TITLE
Play using youtube is facing problems

### ISSUE THREAD

**Issue by NIteshx2** [the-ethan-hunt/B.E.N.J.I.#99]
When i tried to a play a song using "Play rockabye"
wrong link opens, most probably due to google ads **https://www.youtube.comhttps//googleads.g.doubleclick.net/aclk?**sa=l&ai=CmQlG1qFHWuWvNOORlAPg9oegDuDCmM9P2LXV9uEGwI23ARABIOP7kwNg5eLog_gpoAHe47ShA8gBAakCxjb9borPUD6oAwGqBKMBT9Cp6GTnbSXNOALv1JYogMJxX_ovvZYN6j_0HWjAnKl1Gug11lP9uTSTLtCUCshjM2vPMEAJwDrJ6_gtUNqY9fM7qNp-4uOLJLZmU5yPAtVeeQIP-lNcQDotabottXLa3e1p7Wk6DclUqafMRZCcOQN7PqwSir9YiEmLS5GPnYp8qTVddDM_ZUOgqCnbR8sAPioypgKUIUqXUbz-3EiQtnKtzKAGGsgGhIO6lYMHgAeKnMteqAemvhvYBwHSCAcIgGEQARgDsQkLCIwqM_q5RIAKAbgT6AHYEwI&num=1&sig=AOD64_3ICsBEUfJ2qr9qHzbGzRbulTGZ0A&ctype=21&video_id=GmvGVFtLrAI&client=ca-pub-6219811747049371&adurl=http://www.youtube.com/channel/UC7EwKO5tK6HvHM_irHUhQHw%3Fv%3DGmvGVFtLrA

**Comment by the-ethan-hunt** [comment]
Hmm, the problem is occurring. Is it only in Windows or other OS also?

**Comment by the-ethan-hunt** [comment]
Edit: This issue is occurring on all operating systems. Changing the issue labels
**THIS ISSUE IS NOT A KWoC ISSUE. Your PR will not be counted in the official stats**
